# Generated by Django 4.1.3 on 2022-11-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='depart_ment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Emp_dept',
        ),
    ]
