# Generated by Django 4.1.3 on 2022-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_department_id_department_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
