# Generated by Django 4.1.3 on 2022-11-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_dept_id_alter_employee_e_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depart_ment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='your text'),
        ),
    ]
