# Generated by Django 4.1.3 on 2022-11-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_depart_ment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depart_ment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
